services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-list
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:secret@mongodb:27017/task-list?authSource=admin
    profiles:
      - run-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.9
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: task-list
