services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-list
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:secret@mongodb:27017/task-list?authSource=admin
    profiles:
      - run-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.9
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: task-list

  prometheus:
    image: prom/prometheus:v3.4.0
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      - ./config/docker-compose/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    volumes:
      - ./config/docker-compose/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana-data:/var/lib/grafana

  jaeger:
    image: jaegertracing/jaeger:2.6.0
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
      SPAN_STORAGE_TYPE: memory
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

volumes:
  grafana-data:
